### ISSUE TITLE
No publishable resources for tag [laravel-filament-image-generator-field-config].

### ISSUE THREAD

**Issue by bardolf69** [naturalGroove/laravel-filament-image-generator-field#1]
When I try to run ```php artisan vendor:publish --tag="laravel-filament-image-generator-field-config"``` I get ```No publishable resources for tag [laravel-filament-image-generator-field-config].```

Same with ```php artisan vendor:publish --tag="laravel-filament-image-generator-field-views"```

**Comment by naturalGroove** [comment]
There was wrong commands to publish views and config file.
Command should be without "laravel-" on the begining.
README is already updated and new release created. Sorry for the confusion.
