### ISSUE TITLE
symfony/http-client

### ISSUE THREAD

**Issue by Alirezayl** [naturalGroove/laravel-filament-image-generator-field#3]
Hi first of all  thank you for building this great package 
the problem is this 
can you update the version of symfony/http-client  to "^6.4|^7.1.4"

- naturalgroove/laravel-filament-image-generator-field dev-master requires symfony/http-client ^6.4 -> found symfony/http-client[v6.4.0, ..., v6.4.16] but the package is fixed to v7.1.4
thank you

**Comment by naturalGroove** [comment]
Hi, thanks :)
I've updated composer.json to allow symfony/http-client version greater than 7.1.4
